name: Dev Deploy

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:${{ github.sha }}

      # Push to EC2 using private key
      - name: Push to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.ACTION_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            sudo docker pull ${{ env.REGISTRY }}/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:${{ github.sha }}
            sudo docker stop ${{ secrets.DOCKER_CONTAINER_NAME }}
            sudo docker rm ${{ secrets.DOCKER_CONTAINER_NAME }}
            sudo docker run -d -p ${{ secrets.SERVER_PORT }}:${{ secrets.APPLICATION_PORT }} --name ${{ secrets.DOCKER_CONTAINER_NAME }} ${{ env.REGISTRY }}/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:${{ github.sha }}